# ---- Apache (httpd) Hello World ----
FROM httpd:2.4

# httpd serves everything inside /usr/local/apache2/htdocs/
COPY index.html /usr/local/apache2/htdocs/index.html

EXPOSE 80
# base image already runs: httpd-foreground
